"""License-gated external MediaCrawler process integration."""

from .bridge import (
    LEGACY_MANIFEST_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    BridgeConfigurationError,
    BridgeRequest,
    MediaCrawlerBridge,
    MediaCrawlerRunMode,
    MediaCrawlerRunSpec,
    PrivateRunnerInputs,
    RunnerManifest,
)
from .checkout import (
    CheckoutValidationError,
    LicenseAcknowledgementRequired,
    VerifiedCheckout,
    VerifiedPython,
    verify_mediacrawler_checkout,
    verify_mediacrawler_python,
)
from .envelope import MediaCrawlerEnvelope
from .policies import (
    FullHistoryAcknowledgementRequired,
    MediaCrawlerPolicyError,
    OutputInspectionError,
    OutputLimitKind,
    OutputStats,
    WatchdogLimits,
)
from .receipt import (
    COMPLETION_RECEIPT_SCHEMA_VERSION,
    LEGACY_COMPLETION_RECEIPT_SCHEMA_VERSION,
    CompletionReceipt,
    CompletionReceiptError,
    CompletionReceiptErrorCode,
    CompletionReceiptFile,
    JsonlSnapshotFile,
    ValidatedOutputSnapshot,
    completion_receipt_path,
    load_validated_output_snapshot,
)
from .runner import (
    AttemptCleanupError,
    AttemptCleanupStatus,
    MediaCrawlerProcessResult,
    MediaCrawlerProcessRunner,
    MediaCrawlerProcessStatus,
    cleanup_attempt_root,
)
from .subscription_policy import (
    MAX_REQUEST_DELAY_SECONDS,
    SUBSCRIPTION_POLICY_SCHEMA_VERSION,
    MediaCrawlerSubscriptionPolicy,
    MediaCrawlerSubscriptionPolicyError,
    from_subscription_policy,
)

__all__ = [
    "COMPLETION_RECEIPT_SCHEMA_VERSION",
    "LEGACY_COMPLETION_RECEIPT_SCHEMA_VERSION",
    "LEGACY_MANIFEST_SCHEMA_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "MAX_REQUEST_DELAY_SECONDS",
    "SUBSCRIPTION_POLICY_SCHEMA_VERSION",
    "AttemptCleanupError",
    "AttemptCleanupStatus",
    "BridgeConfigurationError",
    "BridgeRequest",
    "CheckoutValidationError",
    "CompletionReceipt",
    "CompletionReceiptError",
    "CompletionReceiptErrorCode",
    "CompletionReceiptFile",
    "FullHistoryAcknowledgementRequired",
    "JsonlSnapshotFile",
    "LicenseAcknowledgementRequired",
    "MediaCrawlerBridge",
    "MediaCrawlerEnvelope",
    "MediaCrawlerPolicyError",
    "MediaCrawlerProcessResult",
    "MediaCrawlerProcessRunner",
    "MediaCrawlerProcessStatus",
    "MediaCrawlerRunMode",
    "MediaCrawlerRunSpec",
    "MediaCrawlerSubscriptionPolicy",
    "MediaCrawlerSubscriptionPolicyError",
    "OutputInspectionError",
    "OutputLimitKind",
    "OutputStats",
    "PrivateRunnerInputs",
    "RunnerManifest",
    "ValidatedOutputSnapshot",
    "VerifiedCheckout",
    "VerifiedPython",
    "WatchdogLimits",
    "cleanup_attempt_root",
    "completion_receipt_path",
    "from_subscription_policy",
    "load_validated_output_snapshot",
    "verify_mediacrawler_checkout",
    "verify_mediacrawler_python",
]
