"""License-gated external MediaCrawler process integration."""

from .account_lock import MediaCrawlerAccountLock
from .bridge import (
    LEGACY_MANIFEST_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    BridgeConfigurationError,
    BridgeRequest,
    MediaCrawlerBridge,
    MediaCrawlerRunMode,
    MediaCrawlerRunSpec,
    PrivateRunnerInputs,
    RunnerManifest,
    SavedSessionUnavailableError,
)
from .checkout import (
    CheckoutValidationCode,
    CheckoutValidationError,
    LicenseAcknowledgementRequired,
    VerifiedCheckout,
    VerifiedPython,
    verify_mediacrawler_browser,
    verify_mediacrawler_checkout,
    verify_mediacrawler_python,
)
from .detail_runner import (
    DETAIL_RUNNER_SCHEMA_VERSION,
    MediaCrawlerDetailPayloadRunner,
    MediaCrawlerDetailProcessRunner,
    MediaCrawlerDetailRequest,
    MediaCrawlerDetailResult,
)
from .envelope import MediaCrawlerEnvelope
from .login import (
    MediaCrawlerLoginMode,
    MediaCrawlerLoginRequest,
    MediaCrawlerLoginResult,
    MediaCrawlerLoginRunner,
    MediaCrawlerLoginStatus,
)
from .login_runner import (
    LOGIN_ONLY_CRAWLER_TYPE,
    LOGIN_RUNNER_SCHEMA_VERSION,
    MediaCrawlerLoginProcessRunner,
    SavedSessionQrFallbackBlocked,
    fence_saved_session_qr_fallback,
)
from .policies import (
    FullHistoryAcknowledgementRequired,
    MediaCrawlerPolicyError,
    OutputInspectionError,
    OutputLimitKind,
    OutputStats,
    WatchdogLimits,
)
from .receipt import (
    COMPLETION_RECEIPT_SCHEMA_VERSION,
    LEGACY_COMPLETION_RECEIPT_SCHEMA_VERSION,
    CompletionReceipt,
    CompletionReceiptError,
    CompletionReceiptErrorCode,
    CompletionReceiptFile,
    JsonlSnapshotFile,
    ValidatedOutputSnapshot,
    completion_receipt_path,
    load_validated_output_snapshot,
)
from .refresh import MediaCrawlerLocatorRefresher, MediaCrawlerRefreshContext
from .runner import (
    AttemptCleanupError,
    AttemptCleanupStatus,
    MediaCrawlerProcessResult,
    MediaCrawlerProcessRunner,
    MediaCrawlerProcessStatus,
    cleanup_attempt_root,
)
from .subscription_policy import (
    MAX_REQUEST_DELAY_SECONDS,
    SUBSCRIPTION_POLICY_SCHEMA_VERSION,
    MediaCrawlerSubscriptionPolicy,
    MediaCrawlerSubscriptionPolicyError,
    from_subscription_policy,
)
from .xhs_authority import validate_xhs_creator_reference, validate_xhs_detail_reference

__all__ = [
    "COMPLETION_RECEIPT_SCHEMA_VERSION",
    "DETAIL_RUNNER_SCHEMA_VERSION",
    "LEGACY_COMPLETION_RECEIPT_SCHEMA_VERSION",
    "LEGACY_MANIFEST_SCHEMA_VERSION",
    "LOGIN_ONLY_CRAWLER_TYPE",
    "LOGIN_RUNNER_SCHEMA_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "MAX_REQUEST_DELAY_SECONDS",
    "SUBSCRIPTION_POLICY_SCHEMA_VERSION",
    "AttemptCleanupError",
    "AttemptCleanupStatus",
    "BridgeConfigurationError",
    "BridgeRequest",
    "CheckoutValidationCode",
    "CheckoutValidationError",
    "CompletionReceipt",
    "CompletionReceiptError",
    "CompletionReceiptErrorCode",
    "CompletionReceiptFile",
    "FullHistoryAcknowledgementRequired",
    "JsonlSnapshotFile",
    "LicenseAcknowledgementRequired",
    "MediaCrawlerAccountLock",
    "MediaCrawlerBridge",
    "MediaCrawlerDetailPayloadRunner",
    "MediaCrawlerDetailProcessRunner",
    "MediaCrawlerDetailRequest",
    "MediaCrawlerDetailResult",
    "MediaCrawlerEnvelope",
    "MediaCrawlerLocatorRefresher",
    "MediaCrawlerLoginMode",
    "MediaCrawlerLoginProcessRunner",
    "MediaCrawlerLoginRequest",
    "MediaCrawlerLoginResult",
    "MediaCrawlerLoginRunner",
    "MediaCrawlerLoginStatus",
    "MediaCrawlerPolicyError",
    "MediaCrawlerProcessResult",
    "MediaCrawlerProcessRunner",
    "MediaCrawlerProcessStatus",
    "MediaCrawlerRefreshContext",
    "MediaCrawlerRunMode",
    "MediaCrawlerRunSpec",
    "MediaCrawlerSubscriptionPolicy",
    "MediaCrawlerSubscriptionPolicyError",
    "OutputInspectionError",
    "OutputLimitKind",
    "OutputStats",
    "PrivateRunnerInputs",
    "RunnerManifest",
    "SavedSessionQrFallbackBlocked",
    "SavedSessionUnavailableError",
    "ValidatedOutputSnapshot",
    "VerifiedCheckout",
    "VerifiedPython",
    "WatchdogLimits",
    "cleanup_attempt_root",
    "completion_receipt_path",
    "fence_saved_session_qr_fallback",
    "from_subscription_policy",
    "load_validated_output_snapshot",
    "validate_xhs_creator_reference",
    "validate_xhs_detail_reference",
    "verify_mediacrawler_browser",
    "verify_mediacrawler_checkout",
    "verify_mediacrawler_python",
]
