"""SQLAlchemy persistence package.

Repositories consume an explicit ``Session``.  ``Database.session()`` owns the
outer transaction so callers can combine multiple repository operations.
"""

from .asset_identity import ASSET_IDENTITY_VERSION, AssetFingerprints, asset_fingerprints
from .base import Base, UTCDateTime, new_uuid, utc_now
from .database import Database, create_database_engine
from .mediacrawler_ingestion import (
    IngestionMode,
    MediaCrawlerIngestionResult,
    MediaCrawlerIngestionService,
)
from .migration import upgrade_database
from .models import (
    ACTIVE_OPERATION_STATES,
    OPERATION_EVENT_CODES,
    OPERATION_EVENT_LEVELS,
    OPERATION_FAILURE_STATES,
    OPERATION_KINDS,
    OPERATION_STATES,
    OPERATION_SUBJECT_ROLES,
    OPERATION_SUBJECT_TYPES,
    TERMINAL_OPERATION_STATES,
    Account,
    Asset,
    AssetRefreshSource,
    Author,
    Content,
    ExportRecord,
    Job,
    LoginSession,
    Operation,
    OperationEvent,
    OperationEventStreamState,
    OperationSubject,
    RunEvent,
    SchedulerLane,
    Subscription,
    SyncRun,
)
from .operation_repository import (
    OperationConflictError,
    OperationError,
    OperationEventCursorError,
    OperationEventSnapshot,
    OperationLease,
    OperationLeaseLostError,
    OperationPayloadError,
    OperationRecoveryCandidate,
    OperationRepository,
    OperationSnapshot,
    OperationStartResult,
    OperationStateConflictError,
    OperationSubjectInput,
    OperationSubjectSnapshot,
)
from .repositories import (
    AccountLoginConflictError,
    AccountRepository,
    AssetConflictError,
    AssetLeaseLostError,
    AssetRefreshSourceRepository,
    AssetRepository,
    AssetUpsert,
    AuthorRepository,
    AuthorUpsert,
    ContentUpsert,
    ExpiredLoginSessionCandidate,
    ExportRecordConflictError,
    ExportRecordRepository,
    JobRepository,
    LeaseLostError,
    LoginSessionConflictError,
    LoginSessionRepository,
    LoginSessionState,
    NotFoundError,
    RepositoryError,
    StaleCheckpointError,
    SubscriptionRepository,
    SyncRunRepository,
)
from .sync_repository import SQLAlchemySyncRepository

__all__ = [
    "ACTIVE_OPERATION_STATES",
    "ASSET_IDENTITY_VERSION",
    "OPERATION_EVENT_CODES",
    "OPERATION_EVENT_LEVELS",
    "OPERATION_FAILURE_STATES",
    "OPERATION_KINDS",
    "OPERATION_STATES",
    "OPERATION_SUBJECT_ROLES",
    "OPERATION_SUBJECT_TYPES",
    "TERMINAL_OPERATION_STATES",
    "Account",
    "AccountLoginConflictError",
    "AccountRepository",
    "Asset",
    "AssetConflictError",
    "AssetFingerprints",
    "AssetLeaseLostError",
    "AssetRefreshSource",
    "AssetRefreshSourceRepository",
    "AssetRepository",
    "AssetUpsert",
    "Author",
    "AuthorRepository",
    "AuthorUpsert",
    "Base",
    "Content",
    "ContentUpsert",
    "Database",
    "ExpiredLoginSessionCandidate",
    "ExportRecord",
    "ExportRecordConflictError",
    "ExportRecordRepository",
    "IngestionMode",
    "Job",
    "JobRepository",
    "LeaseLostError",
    "LoginSession",
    "LoginSessionConflictError",
    "LoginSessionRepository",
    "LoginSessionState",
    "MediaCrawlerIngestionResult",
    "MediaCrawlerIngestionService",
    "NotFoundError",
    "Operation",
    "OperationConflictError",
    "OperationError",
    "OperationEvent",
    "OperationEventCursorError",
    "OperationEventSnapshot",
    "OperationEventStreamState",
    "OperationLease",
    "OperationLeaseLostError",
    "OperationPayloadError",
    "OperationRecoveryCandidate",
    "OperationRepository",
    "OperationSnapshot",
    "OperationStartResult",
    "OperationStateConflictError",
    "OperationSubject",
    "OperationSubjectInput",
    "OperationSubjectSnapshot",
    "RepositoryError",
    "RunEvent",
    "SQLAlchemySyncRepository",
    "SchedulerLane",
    "StaleCheckpointError",
    "Subscription",
    "SubscriptionRepository",
    "SyncRun",
    "SyncRunRepository",
    "UTCDateTime",
    "asset_fingerprints",
    "create_database_engine",
    "new_uuid",
    "upgrade_database",
    "utc_now",
]
